name: CI lint nodejs

on:
  push:
    branches:
      - develop

jobs:
  Build-Nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: 'Compress node_modules folder'
        run: tar -czvf node_modules.tgz node_modules/

      - name: 'Compress public folder'
        run: tar -czvf public.tgz public/

      - name: Upload node_modules assets
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules.tgz
          retention-days: 3

      - name: Upload public folder
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public.tgz
          retention-days: 3

  Test-Prettier:
    runs-on: ubuntu-latest
    needs: [Build-Nodejs]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download node_modules artifacts
        uses: actions/download-artifact@v2
        with:
          name: node_modules

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Unpack artifacts
        run: tar xvfz node_modules.tgz

      - name: Pettier
        run: npm run lint